function newQuat = quatMult(oldQuat, rot)   
    newQuat = zeros(1,4);
    
    newQuat(1) = rot(1)*oldQuat(1) - rot(2)*oldQuat(2) - rot(3)*oldQuat(3)...
        - rot(4)*oldQuat(4);
    newQuat(2) = rot(1)*oldQuat(2) + rot(2)*oldQuat(1) - rot(3)*oldQuat(4)...
        + rot(4)*oldQuat(3);
    newQuat(3) = rot(1)*oldQuat(3) + rot(2)*oldQuat(4) + rot(3)*oldQuat(1)...
        - rot(4)*oldQuat(2);
    newQuat(4) = rot(1)*oldQuat(4) - rot(2)*oldQuat(3) + rot(3)*oldQuat(2)...
        + rot(4)*oldQuat(1);
end